homeassistant:
  name: HA_test
  elevation: 123

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

http:
  base_url: https://q12w.duckdns.org
  ssl_key: /home/sa/.homeassistant/privkey.pem
  ssl_certificate: /home/sa/.homeassistant/fullchain.pem

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

google_assistant:
  project_id: project2-9ec8b
  service_account: !include SERVICE_ACCOUNT.JSON
  report_state: true
  exposed_domains:
    - switch
    - light

restart_ha:
  alias: Перезапускаем Home Assistant
  sequence:
    - alias: Restart Home Assistant
      service: homeassistant.restart

switch:
  - platform: template
    switches:
      skylight:
        value_template: "{{ is_state('sensor.skylight', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.skylight_open
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.skylight_close

binary_sensor:
  - platform: ping
    host: 10.10.11.100
    name: OpenVPN
    count: 2
    scan_interval: 30

sensor:
  - platform: systemmonitor
    resources:
    - type: processor_use
    - type: memory_use_percent
    - type: disk_free
      arg: /

  - platform: command_line
    name: GPU Temperature
    command: "sudo /opt/vc/bin/vcgencmd measure_temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | replace("temp=", "") | replace("''C", "") }}'

  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    # If errors occur, make sure configuration file is encoded as UTF-8
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'


#google_assistant:
#  project_id: project2-9ec8b
#  api_key: AIzaSyBuxrQOUNQGIqn4L4gME3cAHbm8uG3eGEQ
#  exposed_domains:
#    - light