title: HA_V
views:
  - title: Главная
    icon: mdi:home-assistant
    cards:

  - title: local host
    icon: mdi:desktop-tower
    cards:
    - type: horizontal-stack
      cards:
      - type: gauge
        name: Загрузка CPU
        unit: "%"
        entity: sensor.processor_use
        severity:
          green: 0
          yellow: 60
          red: 85
      - type: gauge
        name: Загрузка ОЗУ
        unit: "%"
        entity: sensor.memory_use_percent
        severity:
          green: 0
          yellow: 60
          red: 85
      - type: gauge
        name: Свободно на SD
        unit: "Гб"
        max: 64
        entity: sensor.disk_free
        severity:
          green: 48
          yellow: 24
          red: 4
      
#icon: mdi: source https://materialdesignicons.com/
#    - type: horizontal-stack
#     cards: sensor.disk_free sun.sun